name: login_app_backend
description: A backend service for the login application.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  mongo_dart: ^0.8.0
  googleapis: ^9.0.0
  googleapis_auth: ^1.0.0
  dotenv: ^4.2.0
dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  test: ^1.16.0
